# Determine system architecture
set(PLATFORM "<unknown>")
if(${CMAKE_SIZEOF_VOID_P} STREQUAL 4)
    set(ARCH "x86")
    if(WIN32)
        set(PLATFORM "win32")
    endif()
    if(UNIX)
        set(PLATFORM "linux32")
    endif()
elseif(${CMAKE_SIZEOF_VOID_P} STREQUAL 8)
    set(ARCH "x64")
    if(WIN32)
        set(PLATFORM "win64")
    endif()
    if(UNIX)
        set(PLATFORM "linux64")
    endif()
endif()
